package:
  name: SDT 2
  version: 1.0.0

source:
  path: .

build:
  script: python -m pip install .

requirements:
  build:
    - python
    - pip
    - pywebview
    - biopython
    - numpy
    - scipy
    - psutil
    - pandas
    - parasail
  run:
    - python >=3.9

    - pywebview

about:
  home: https://github.com/SDT-org/SDT2
  summary: "SDT2 is a sequence classification tool based on percent identities from
      pairwise sequence alignments"
  license: MIT
