name: Build SDT2
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: ubuntu-latest
            arch: x64
          - os: ubuntu-22.04
            arch: arm64
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install virtualenv
        run: pip install virtualenv

      - uses: oven-sh/setup-bun@v2

      - name: Run init
        run: bun run init

      - name: Run build
        run: bun run build

      - name: macOS - Prepare artifact
        if: matrix.os == 'macos-latest'
        run: |
          cd build
          zip -r SDT2.app.zip SDT2.app

      - name: Ubuntu - Set execute permissions
        if: matrix.os == 'ubuntu-latest' || (matrix.os == 'ubuntu-22.04' && matrix.arch == 'arm64')
        run: chmod +x build/SDT2

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build-output
          path: |
            ${{ matrix.os == 'windows-latest' && 'build/SDT2.exe' || '' }}
            ${{ matrix.os == 'macos-latest' && 'build/SDT2.app.zip' || '' }}
            ${{ matrix.os == 'ubuntu-latest' && 'build/SDT2' || '' }}
            ${{ matrix.os == 'ubuntu-22.04' && matrix.arch == 'arm64' && 'build/SDT2' || '' }}
