name: Build SDT2
on:
  push:
    tags:
      - '*'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Universal Setup
        uses: ./.github/actions/setup
        with:
          python-version: '3.11'
      - name: macOS arm64 Build
        uses: ./.github/actions/build
        with:
          os-type: macos
      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build-output
          path: build/SDT2.app.zip

  build-macos-x86_64:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Universal Setup
        uses: ./.github/actions/setup
        with:
          python-version: '3.11'
      - name: macOS x86_64 Build
        uses: ./.github/actions/build
        with:
          os-type: macos
      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build-x86_64-output
          path: build/SDT2.app.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Universal Setup
        uses: ./.github/actions/setup
        with:
          python-version: '3.11'
      - name: Linux-Specific Build
        uses: ./.github/actions/build
        with:
          os-type: ubuntu
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-output
          path: build/SDT2.tar.gz

  build-windows-onefile:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Universal Setup
        uses: ./.github/actions/setup
        with:
          python-version: '3.11'
      - name: Windows Build Onefile
        uses: ./.github/actions/build
        with:
          os-type: windows
      - name: Upload Windows Onefile Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-onefile
          path: build/SDT2.exe

  build-windows-standalone:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Universal Setup
        uses: ./.github/actions/setup
        with:
          python-version: '3.11'
      - name: Windows Build Standalone
        uses: ./.github/actions/build
        with:
          os-type: windows
          extra-flags: --skip-onefile
      - name: Upload Windows Standalone Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-standalone
          path: build/SDT2.zip
